[build]
  base = "app"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://my-url-shorten.netlify.app/*"
  to = "https://myurl.mannayuvatha.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://s.myfervera.in/*"
  to = "https://myurl.mannayuvatha.com/:splat"
  status = 301
  force = true
